version: 2

models:
  - name: stg_trades
    columns:
      - name: trade_id
        data_tests:
          - unique
          - not_null
      - name: trade_price_usd
        data_tests:
          - not_null
      - name: trade_type
        data_tests:
          - accepted_values:
              arguments:
                values: ['Physical Buy', 'Physical Sell', 'Futures Hedge']
      - name: eudr_status
        data_tests:
          - accepted_values:
              arguments:
                values: ['Verified', 'Pending Polygon Mapping']

  - name: stg_shipments
    columns:
      - name: container_id
        data_tests:
          - unique
          - not_null
      - name: trade_id
        data_tests:
          - relationships:
              arguments:
                to: ref('stg_trades')
                field: trade_id